// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJyFQxayc-XkT0-AG4qRmyyRoA25hLZSU',
    appId: '1:568840500328:web:27180323eb488b532bb7dd',
    messagingSenderId: '568840500328',
    projectId: 'pontosolu',
    authDomain: 'pontosolu.firebaseapp.com',
    databaseURL: 'https://pontosolu-default-rtdb.firebaseio.com',
    storageBucket: 'pontosolu.appspot.com',
    measurementId: 'G-F9EDD4ZHWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO5p7I0UpjXYWn329qoLWacHnjVbNz2oU',
    appId: '1:568840500328:android:742e41e31c1f6c882bb7dd',
    messagingSenderId: '568840500328',
    projectId: 'pontosolu',
    databaseURL: 'https://pontosolu-default-rtdb.firebaseio.com',
    storageBucket: 'pontosolu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApia1aWs2ad58h1UnsU0Vb30iQQ7-B7lM',
    appId: '1:568840500328:ios:9160782f78bd20822bb7dd',
    messagingSenderId: '568840500328',
    projectId: 'pontosolu',
    databaseURL: 'https://pontosolu-default-rtdb.firebaseio.com',
    storageBucket: 'pontosolu.appspot.com',
    iosClientId: '568840500328-92tb7qp1p7e40aah2bvsbs47rpee2ifj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pontosolu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApia1aWs2ad58h1UnsU0Vb30iQQ7-B7lM',
    appId: '1:568840500328:ios:9160782f78bd20822bb7dd',
    messagingSenderId: '568840500328',
    projectId: 'pontosolu',
    databaseURL: 'https://pontosolu-default-rtdb.firebaseio.com',
    storageBucket: 'pontosolu.appspot.com',
    iosClientId: '568840500328-92tb7qp1p7e40aah2bvsbs47rpee2ifj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pontosolu',
  );
}
